export const GET_COURS = 'GET_COURS';
export const TOGGLE_COURCE = 'TOGGLE_COURCE';

export const GET_ALLCURRENCIES = 'GET_ALLCURRENCIES';
export const TOGGLE_ALLCURRENCIES = 'TOGGLE_ALLCURRENCIES';
export const GET_RATE = 'GET_RATE';
export const GET_FIRSTNAME = 'GET_FIRSTNAME';
export const GET_SECONDNAME = 'GET_SECONDNAME';
